stages:
  - test
  - build
  - deploy
  - cleanup

before_script:
  - echo "Stage Started for " $CI_COMMIT_REF_NAME
  - export PATH=$PATH:/usr/local/bin

test:
  tags:
    - dspg_dev
  stage: test
  script:
    - pip3.6 install --upgrade pip
    - pip3.6 install -r requirements.txt
    - python3.6 -m nltk.downloader punkt
    - python3.6 -m nltk.downloader wordnet
    - python3.6 -m nltk.downloader averaged_perceptron_tagger
    - python3.6 -m spacy download en_core_web_sm
    - python3.6 -m pytest --html=report.html --cov=bot_trainer tests/ --cov-report html:coverage_html



build:
  tags:
    - dspg
  only:
    - master
  stage: build
  script:
    - docker build -t bot-trainer-api:0.1 -f docker/Dockerfile_api

cleanup:
  stage: cleanup
  script:
    - docker image prune -a --force --filter "until=60h"