stages:
  - test
  - build
  - deploy
  - cleanup

before_script:
  - echo "Stage Started for " $CI_COMMIT_REF_NAME
  - export PATH=$PATH:/usr/local/bin

test:
  tags:
    - dspg_dev
  stage: test
  script:
    - pip3.6 install --upgrade pip
    - pip3.6 install -r requirements.txt
    - python3.6 -m spacy download en_core_web_sm
    - python3.6 -m gensim.downloader --download word2vec-google-news-300
    - python3.6 -m pytest --html=report.html --cov=bot_trainer tests/ --cov-report html:coverage_html



build:
  tags:
    - dspg
  only:
    - master
  stage: build
  script:
    -  docker build -f ./docker/Dockerfile_api -t bot-trainer-api:0.1 .
    -  docker build -f ./docker/Dockerfile_augment -t bot-augment-api:0.1 .

cleanup:
  stage: cleanup
  script:
    - docker image prune -a --force --filter "until=60h"