# This workflow will scan the created docker images at scheduled time and create issue if vulnerability is found
name: Vulnerability Scan

on:
  schedule:
    - cron: '30 5 * * 0'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker images
        run: |
          docker pull digite/kairon-api
          docker pull digite/kairon-ui
          docker pull digite/kairon-action-server
          docker pull digite/kairon-history-server
          docker pull digite/kairon-chat
          docker pull digite/kairon-paraphrase
          docker pull digite/kairon-qg
      - uses: Azure/container-scan@v0.1
        name: Scanning api image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-api
      - uses: Azure/container-scan@v0.1
        name: Scanning ui image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-ui
      - uses: Azure/container-scan@v0.1
        name: Scanning action image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-action-server
      - uses: Azure/container-scan@v0.1
        name: Scanning history image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-history-server
      - uses: Azure/container-scan@v0.1
        name: Scanning chat image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-chat
      - uses: Azure/container-scan@v0.1
        name: Scanning paraphrase image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-paraphrase
      - uses: Azure/container-scan@v0.1
        name: Scanning question generation image
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: digite/kairon-qg